# Generated by Django 5.2.8 on 2025-12-09 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_node_edge_workflowshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to=settings.AUTH_USER_MODEL),
        ),
    ]
